# Generated by Django 6.0.3 on 2026-06-04 05:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0003_order_gross_profit_order_total_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('account_type', models.CharField(choices=[('cash', 'خزنة نقدية'), ('bank', 'حساب بنكي'), ('wallet', 'محفظة إلكترونية'), ('sales_rep_cash', 'عهدة مندوب مالية')], db_index=True, default='cash', max_length=30)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allow_overdraft', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('customer_payment', 'تحصيل من عميل'), ('supplier_payment', 'دفع لمورد'), ('expense', 'مصروف'), ('refund', 'استرداد للعميل'), ('sales_rep_collection', 'تحصيل مندوب'), ('transfer', 'تحويل بين الخزن'), ('adjustment', 'تسوية رصيد')], db_index=True, max_length=40)),
                ('direction', models.CharField(choices=[('in', 'داخل'), ('out', 'خارج')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('related_supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=80, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.cashaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='customers.customer')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='orders.order')),
                ('related_sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='finance_cas_account_e6a7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['created_at'], name='finance_cas_created_6469c9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='finance_pay_transac_11d845_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['direction', 'created_at'], name='finance_pay_directi_725946_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['cash_account', 'created_at'], name='finance_pay_cash_ac_e54dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['related_order'], name='finance_pay_related_3d9afb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['related_customer'], name='finance_pay_related_90295e_idx'),
        ),
    ]
