# Generated by Django 6.0.3 on 2026-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymenttransaction_related_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('customer_payment', 'تحصيل من عميل'), ('supplier_payment', 'دفع لمورد'), ('expense', 'مصروف'), ('refund', 'استرداد للعميل'), ('sales_rep_collection', 'تحصيل مندوب'), ('transfer', 'تحويل بين الخزن'), ('adjustment', 'تسوية رصيد'), ('sales_rep_handover', 'Sales rep handover')], db_index=True, max_length=40),
        ),
    ]
