# Generated by Codex on 2026-06-07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_paymenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
