# Generated by Django 6.0.3 on 2026-06-08 09:51

from django.conf import settings
from django.db import migrations, models
from config.django_compat import check_constraint


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_credit_limit_customer_opening_balance_and_more'),
        ('finance', '0004_paymenttransaction_transaction_date'),
        ('orders', '0008_alter_order_payment_method'),
        ('purchases', '0002_purchaseorderitem_purchases_purchaseorderitem_quantity_gt_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_type', 'direction', 'transaction_date'], name='finance_pay_transac_735410_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='finance_pay_created_305de2_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=check_constraint(check=models.Q(('amount__gt', 0)), name='finance_paymenttransaction_amount_gt_0'),
        ),
    ]
