# Generated by Django 6.0.3 on 2026-06-04 06:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('finance', '0003_alter_paymenttransaction_transaction_type'),
        ('inventory', '0005_alter_stockmovement_movement_type'),
        ('orders', '0004_alter_order_status'),
        ('products', '0002_productvariant_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('handed_over_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('collection_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('handed_over', models.BooleanField(db_index=True, default=False)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_rep_collections', to='finance.cashaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_rep_collections', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_collections', to='customers.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rep_collections', to='orders.order')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['sales_rep', 'handed_over'], name='sales_reps__sales_r_614bcf_idx'), models.Index(fields=['collection_date'], name='sales_reps__collect_1671e3_idx'), models.Index(fields=['order'], name='sales_reps__order_i_442889_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesRepStockAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_assigned', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('quantity_remaining', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_assignments', to=settings.AUTH_USER_MODEL)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_rep_assignments', to='products.productvariant')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_assignments', to=settings.AUTH_USER_MODEL)),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_rep_assignments', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['sales_rep', 'is_active'], name='sales_reps__sales_r_cf0523_idx'), models.Index(fields=['product_variant', 'sales_rep'], name='sales_reps__product_f4d642_idx'), models.Index(fields=['assigned_at'], name='sales_reps__assigne_fc1d1b_idx')],
            },
        ),
    ]
