# Generated by Django 6.0.3 on 2026-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvariant_products_productvariant_cost_price_gte_0_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='purchases_purchaseorderitem_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('received_quantity__gte', 0)), name='purchases_purchaseorderitem_received_quantity_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('unit_cost__gte', 0)), name='purchases_purchaseorderitem_unit_cost_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(check=models.Q(('total_cost__gte', 0)), name='purchases_purchaseorderitem_total_cost_gte_0'),
        ),
    ]
