# Generated by Django 6.0.3 on 2026-06-04 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0004_alter_order_status'),
        ('products', '0002_productvariant_cost_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(choices=[('refund', 'استرداد'), ('exchange', 'استبدال'), ('partial_return', 'مرتجع جزئي')], db_index=True, default='partial_return', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('completed', 'مكتمل'), ('rejected', 'مرفوض')], db_index=True, default='draft', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='customers.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_returns', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('new_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('new_product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_items', to='products.productvariant')),
                ('old_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_items', to='orders.orderitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_items', to='returns.salesreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(choices=[('good', 'سليم'), ('damaged', 'تالف'), ('needs_review', 'يحتاج مراجعة')], db_index=True, default='good', max_length=30)),
                ('return_to_stock', models.BooleanField(default=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('original_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='products.productvariant')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.salesreturn')),
            ],
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['status', 'created_at'], name='returns_sal_status_d97dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['return_type', 'created_at'], name='returns_sal_return__b33cec_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreturn',
            index=models.Index(fields=['order', 'status'], name='returns_sal_order_i_66bdbf_idx'),
        ),
    ]
