# Generated by Django 5.2.17 on 2026-09-02 07:31

import config.branching
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_branch_alter_submissionreceipt_options_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeitem',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='exchangeitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesreturn',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesreturnitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
    ]
