# Generated by Django 6.0.3 on 2026-06-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'مسؤول النظام'), ('sales', 'مندوب مبيعات'), ('warehouse', 'مسؤول مخزن')], db_index=True, default='sales', max_length=20),
        ),
    ]
