# Generated by Django 5.2.17 on 2026-09-02 07:31

import config.branching
import accounts.models
import django.contrib.auth.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


def assign_existing_users(apps, schema_editor):
    Branch = apps.get_model('accounts', 'Branch')
    User = apps.get_model('accounts', 'User')
    branch, _ = Branch.objects.get_or_create(
        code='MAIN',
        defaults={'name': 'المعرض الرئيسي', 'is_active': True},
    )
    User.objects.filter(is_superuser=False, branch__isnull=True).update(branch=branch)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_submissionreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='submissionreceipt',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='submissionreceipt',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='submissionreceipt',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.branch'),
        ),
        migrations.RunPython(assign_existing_users, migrations.RunPython.noop),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.BranchUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
