# Generated by Django 5.2.17 on 2026-09-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_branch_alter_submissionreceipt_options_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            # ``check`` is supported by Django 5.0 (the production version) and
            # remains backwards-compatible with the newer Django version that
            # originally generated this migration.
            constraint=models.CheckConstraint(check=models.Q(('is_superuser', True), ('branch__isnull', False), _connector='OR'), name='accounts_user_non_superuser_requires_branch'),
        ),
    ]
