# Generated by Django 6.0.3 on 2026-06-02 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('warehouse_type', models.CharField(choices=[('main', 'مخزن رئيسي'), ('store', 'محل بيع')], db_index=True, max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'دخول مخزون'), ('out', 'خروج مخزون'), ('transfer', 'تحويل بين مخازن'), ('sale', 'بيع'), ('return', 'مرتجع'), ('adjustment', 'تسوية')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='out_movements', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_movements', to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'), models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['warehouse', 'variant'], name='inventory_s_warehou_0f9a51_idx'), models.Index(fields=['quantity'], name='inventory_s_quantit_287c3e_idx')],
                'unique_together': {('warehouse', 'variant')},
            },
        ),
    ]
