# Generated by Django 6.0.3 on 2026-06-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('main', 'مخزن رئيسي'), ('store', 'محل بيع'), ('representative', 'عهدة مندوب')], db_index=True, max_length=20),
        ),
    ]
