# Generated by Django 6.0.3 on 2026-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_assigned_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'دخول مخزون'), ('out', 'خروج مخزون'), ('transfer', 'تحويل بين مخازن'), ('sale', 'بيع'), ('return', 'مرتجع'), ('adjustment', 'تسوية'), ('purchase_receive', 'Purchase receive')], db_index=True, max_length=20),
        ),
    ]
