# Generated by Django 6.0.3 on 2026-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'دخول مخزون'), ('out', 'خروج مخزون'), ('transfer', 'تحويل بين مخازن'), ('sale', 'بيع'), ('return', 'مرتجع'), ('adjustment', 'تسوية'), ('purchase_receive', 'Purchase receive'), ('sales_return', 'Sales return'), ('damaged_return', 'Damaged return'), ('exchange_out', 'Exchange out')], db_index=True, max_length=20),
        ),
    ]
