# Generated by Django 6.0.3 on 2026-06-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockmovement_movement_type'),
        ('products', '0005_copy_product_price_to_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'دخول مخزون'), ('out', 'خروج مخزون'), ('transfer', 'تحويل بين مخازن'), ('sale', 'بيع'), ('return', 'مرتجع'), ('adjustment', 'تسوية'), ('purchase_receive', 'Purchase receive'), ('sales_return', 'Sales return'), ('damaged_return', 'Damaged return'), ('exchange_out', 'Exchange out'), ('sales_rep_assignment', 'Sales rep assignment'), ('sales_rep_return', 'Sales rep return'), ('sales_rep_sale', 'Sales rep sale'), ('sample', 'Sample / free issue')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(db_index=True, default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='products.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['received_at', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockbatch'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['variant', 'warehouse', 'remaining_quantity'], name='inventory_s_variant_469405_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['received_at'], name='inventory_s_receive_d31c57_idx'),
        ),
    ]
