# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stock_updated_at_stockmovement_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(
                choices=[
                    ('opening_balance', 'رصيد افتتاحي'),
                    ('in', 'دخول مخزون'),
                    ('out', 'خروج مخزون'),
                    ('transfer', 'تحويل بين مخازن'),
                    ('sale', 'بيع'),
                    ('return', 'مرتجع'),
                    ('adjustment', 'تسوية'),
                    ('purchase_receive', 'استلام شراء'),
                    ('purchase_return', 'مرتجع شراء'),
                    ('sales_return', 'مرتجع بيع'),
                    ('damaged_return', 'مرتجع تالف'),
                    ('exchange_out', 'خروج استبدال'),
                    ('sales_rep_assignment', 'تهيئة مندوب'),
                    ('sales_rep_return', 'مرتجع مندوب'),
                    ('sales_rep_sale', 'بيع مندوب'),
                    ('sample', 'عينة / إصدار مجاني'),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
