# Generated by Django 5.2.17 on 2026-09-02 07:31

import config.branching
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_branch_alter_submissionreceipt_options_and_more'),
        ('inventory', '0012_add_opening_balance_movement_type'),
        ('products', '0015_alter_category_managers_alter_color_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='stock',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stockbatch',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stockmovement',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='stock',
            name='stock_warehouse_variant_unique',
        ),
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('branch', 'warehouse', 'variant'), name='stock_warehouse_variant_unique'),
        ),
    ]
