# Generated by Django 6.0.3 on 2026-06-04 07:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('b2c', 'عميل فردي'), ('b2b', 'عميل جملة / شركة'), ('retail', 'قطاعي'), ('wholesale', 'جملة'), ('vip', 'VIP'), ('inactive', 'غير نشط'), ('potential', 'محتمل'), ('problem_customer', 'عميل يحتاج متابعة')], db_index=True, default='retail', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('call', 'مكالمة'), ('whatsapp', 'واتساب'), ('visit', 'زيارة'), ('note', 'ملاحظة'), ('complaint', 'شكوى'), ('follow_up', 'متابعة')], db_index=True, default='note', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('next_follow_up_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_interactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='customers_c_custome_0a29a5_idx'), models.Index(fields=['interaction_type', 'is_completed'], name='customers_c_interac_a2d455_idx'), models.Index(fields=['next_follow_up_date', 'is_completed'], name='customers_c_next_fo_12d7ee_idx')],
            },
        ),
    ]
