# Generated by Django 6.0.3 on 2026-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_credit_limit_customer_opening_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('b2c', 'عميل فردي'), ('b2b', 'عميل جملة / شركة'), ('retail', 'قطاعي'), ('wholesale', 'جملة'), ('inactive', 'غير نشط'), ('potential', 'محتمل'), ('problem_customer', 'عميل يحتاج متابعة')], db_index=True, default='retail', max_length=30),
        ),
    ]
