# Generated by Django 5.2.15 on 2026-07-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_updated_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='customer',
                    new_name='customers_c_sales_r_0449f9_idx',
                    old_name='customers_c_sales__e469cc_idx',
                ),
            ],
        ),
    ]
