# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_customers_c_sales__e469cc_idx_customers_c_sales_r_0449f9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
