# Generated by Django 6.0.3 on 2026-06-08 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('confirm', 'تأكيد'), ('cancel', 'إلغاء'), ('return', 'مرتجع'), ('receive', 'استلام'), ('pay', 'دفع'), ('collect', 'تحصيل'), ('handover', 'تسليم عهدة'), ('assign', 'تعيين'), ('adjust', 'تسوية'), ('transfer', 'تحويل')], db_index=True, max_length=20)),
                ('section', models.CharField(choices=[('products', 'المنتجات'), ('orders', 'الطلبات'), ('inventory', 'المخزون'), ('purchases', 'المشتريات'), ('returns', 'المرتجعات'), ('finance', 'المالية'), ('customers', 'العملاء'), ('sales_reps', 'المندوبين'), ('settings', 'الإعدادات')], db_index=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('changes_before', models.JSONField(blank=True, null=True)),
                ('changes_after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['section', 'created_at'], name='audit_audit_section_aa3cdb_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx')],
            },
        ),
    ]
