# Generated by Django 6.0.3 on 2026-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_gross_profit_order_total_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('preparing', 'قيد التجهيز'), ('ready', 'جاهز'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('returned', 'مرتجع'), ('partially_returned', 'Partially returned')], db_index=True, default='draft', max_length=20),
        ),
    ]
