# Generated by Django 6.0.3 on 2026-06-05 09:35

import django.db.models.deletion
from django.db import migrations, models


def copy_order_warehouse_to_items(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    for item in OrderItem.objects.select_related('order').filter(warehouse__isnull=True):
        if item.order and item.order.warehouse_id:
            item.warehouse_id = item.order.warehouse_id
            item.save(update_fields=['warehouse'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockmovement_movement_type'),
        ('orders', '0005_order_discount_amount_order_discount_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.RunPython(copy_order_warehouse_to_items, noop),
    ]
