# Generated by Django 6.0.3 on 2026-06-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockmovement_movement_type_stockbatch_and_more'),
        ('orders', '0006_orderitem_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('quote', 'Priced quote'), ('sample', 'Sample / free issue')], db_index=True, default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stockbatch'),
        ),
    ]
