# Generated by Django 6.0.3 on 2026-06-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_document_type_orderitem_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('cod', 'الدفع عند الاستلام'), ('bank_transfer', 'تحويل بنكي مسجل يدويا'), ('wallet_transfer', 'تحويل محفظة مسجل يدويا'), ('credit', 'آجل')], default='cash', max_length=30),
        ),
    ]
