# Generated by Django 5.2.17 on 2026-09-02 07:31

import config.branching
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_branch_alter_submissionreceipt_options_and_more'),
        ('customers', '0009_alter_customer_managers_and_more'),
        ('inventory', '0013_alter_warehouse_options_alter_stock_managers_and_more'),
        ('orders', '0009_order_orders_orde_custome_e58380_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='branch',
            field=models.ForeignKey(default=config.branching.get_default_branch_id, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('branch', 'order_number'), name='orders_order_branch_number_unique'),
        ),
    ]
