# Generated by Django 6.0.3 on 2026-06-04 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='allow_manager_sell_below_cost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='max_sales_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='max_vip_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
