# Generated by Django 6.0.3 on 2026-06-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_companysettings_allow_manager_sell_below_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='max_vip_discount_percentage',
        ),
    ]
