# Generated by Codex on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_remove_companysettings_max_vip_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='thermal_paper_width',
            field=models.CharField(
                choices=[('80', '80 مم'), ('58', '58 مم')],
                default='80',
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='thermal_print_mode',
            field=models.CharField(
                choices=[
                    ('browser', 'طباعة المتصفح'),
                    ('electron', 'طباعة مباشرة عبر تطبيق سطح المكتب'),
                    ('qz', 'طباعة مباشرة عبر QZ Tray'),
                ],
                default='browser',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='thermal_printer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
