# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_companysettings_thermal_paper_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='thermal_invoice_font_scale',
            field=models.CharField(
                choices=[
                    ('100', 'عادي'),
                    ('115', 'كبير'),
                    ('130', 'كبير جدًا'),
                ],
                default='115',
                max_length=3,
            ),
        ),
    ]
