# Generated by Codex for the SH desktop sync client.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_api_url', models.URLField(default='https://sh.elwsamstore.com/api/')),
                ('device_id', models.CharField(default=uuid.uuid4, max_length=120, unique=True)),
                ('token', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('last_push_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncEntityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer'), ('order', 'Order')], db_index=True, max_length=40)),
                ('local_uuid', models.CharField(db_index=True, max_length=120)),
                ('local_object_id', models.CharField(db_index=True, max_length=100)),
                ('server_object_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_server_origin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=160, unique=True)),
                ('entity_type', models.CharField(db_index=True, max_length=40)),
                ('operation_type', models.CharField(default='create', max_length=40)),
                ('local_uuid', models.CharField(db_index=True, max_length=120)),
                ('local_object_id', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('conflict', 'Conflict')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('response_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='syncentitymap',
            constraint=models.UniqueConstraint(fields=('entity_type', 'local_object_id'), name='desktop_sync_entity_local_unique'),
        ),
        migrations.AddConstraint(
            model_name='syncentitymap',
            constraint=models.UniqueConstraint(fields=('entity_type', 'local_uuid'), name='desktop_sync_entity_uuid_unique'),
        ),
        migrations.AddIndex(
            model_name='syncoutbox',
            index=models.Index(fields=['status', 'created_at'], name='desktop_syn_status_95d791_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoutbox',
            index=models.Index(fields=['entity_type', 'local_uuid'], name='desktop_syn_entity__9898e3_idx'),
        ),
    ]
