# Generated by Django 6.0.3 on 2026-06-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
