# Generated by Django 6.0.3 on 2026-06-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productvariant_cost_price_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='products_productvariant_cost_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='products_productvariant_sale_price_gte_0'),
        ),
    ]
